# Test Normal model implementation

In [23]:
import numpy as np
from option_models import basket

In [24]:
### only run this when you changed the class definition
import imp
imp.reload(basket)

<module 'option_models.basket' from 'D:\\Mega\\PHBS\\2017 M1 ASP\\SpreadBasketOptions_Base\\option_models\\basket.py'>

In [25]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.2
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.8*np.identity(4) + 0.2*np.ones((4,4))
texp = 1
strike = 102

print(weights)

basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
# write your own normal model pricing here and compare
# do the similar for BSM model

[1 0 0 0]


6.8785699372621272

In [26]:
# A trivial test case 2

# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.2
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 1
strike = 102

print( cor_m )

basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
# write your own normal model pricing here and compare
# do the similar for BSM model

[[ 1.      0.9999  0.9999  0.9999]
 [ 0.9999  1.      0.9999  0.9999]
 [ 0.9999  0.9999  1.      0.9999]
 [ 0.9999  0.9999  0.9999  1.    ]]


6.8796865246458179

In [27]:
# A test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor_m = np.array([[1, 0.5], [0.5, 1]])
texp = 1
strike = 0
price = 8.5132252

In [28]:
# MC price based on normal model
# make sure that the prices are similar\

np.random.seed(123456)
basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)

#basket.basket_price_norm_analytic(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)

8.3488528072252919

In [29]:
# A test set for basket option
spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5*np.ones((4,4))
texp = 5
strike = 100
price = 28.0073695

In [30]:
# MC price based on normal model
# make sure that the prices are similar

basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)

#basket.basket_price_norm_analytic(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)

27.783053422371029